services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    networks:
      - lab-net
      
  grafana:
    image: docker.io/grafana/grafana-oss:10.4.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - lab-net       

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.8.0
    container_name: node-exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'

  pihole-exporter:
    image: docker.io/ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    restart: unless-stopped
    environment:
      PIHOLE_HOSTNAME: 100.112.39.36
      PIHOLE_PASSWORD: 'P@ssw0rd'
      PORT: 9617
    ports:
      - 9617:9617
    networks:
      - lab-net    

networks:
  lab-net:
    external: true

volumes:
  prometheus_data:
    external: true
    
  grafana_data:
    external: true   
