global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['10.0.1.50:9100'] 

  - job_name: 'pihole'
    scrape_interval: 30s
    static_configs:
      - targets: ['pihole-exporter:9617']
